/**
 * Create Knowledge Base Macro
 *
 * AI tool for creating new knowledge bases. Conforms to the standard reactor
 * macro/tool implementation: a `component` function plus a
 * `MacroComponentDefinition` registry entry, resolving services from
 * `state.context.getService(...)`.
 */

import { ChatState, MacroComponentDefinition } from '@reactory/server-modules/reactory-reactor/ai/openai/types/chat';
import { IKnowledgeBaseService } from '@reactory/server-modules/reactory-kb/services/KnowledgeBaseService';
import { ICreateKBInput, KBVisibility } from '@reactory/server-modules/reactory-kb/types/kb.types';

export interface CreateKnowledgeBaseMacroParams {
  /** The title of the knowledge base */
  title: string;
  /** A brief description of what this knowledge base contains */
  description?: string;
  /** Default language code (e.g., "en", "fr", "es") */
  lng?: string;
  /** Visibility setting for the knowledge base */
  visibility?: KBVisibility;
  /** Tags for categorizing the knowledge base */
  tags?: string[];
}

const CreateKnowledgeBaseMacro = async (
  params: CreateKnowledgeBaseMacroParams,
  state: ChatState,
) => {
  const { context } = state;
  const { title, description, lng = 'en', visibility = KBVisibility.PRIVATE, tags = [] } = params;

  if (!title) {
    return {
      success: false,
      error: 'title is required',
      tool: 'create_knowledge_base',
      params,
      instructions: `## Create Knowledge Base — Missing Parameter\n\n**title** is required.\n\n### Recovery Options:\n- Provide a descriptive title and retry`,
    };
  }

  try {
    const kbService = context?.getService<IKnowledgeBaseService>('kb.KnowledgeBaseService@1.0.0');

    if (!kbService) {
      return {
        success: false,
        error: 'KnowledgeBaseService is not available',
        tool: 'create_knowledge_base',
        params,
        instructions: `## Create Knowledge Base — Service Unavailable\n\nThe KnowledgeBaseService is not registered.\n\n### Recovery Options:\n- Use \`svc\` with action="list" to check available services\n- Verify the reactory-kb module is loaded`,
      };
    }

    // `slug` is auto-generated by the service from the title when omitted.
    const kb = await kbService.createKnowledgeBase({
      title,
      description,
      lng,
      visibility,
      tags,
    } as ICreateKBInput);

    if (!state.vars) state.vars = {};
    state.vars.lastCreatedKnowledgeBase = kb;

    return {
      success: true,
      data: {
        id: kb.id,
        slug: kb.slug,
        title: kb.title,
        description: kb.description,
        visibility: kb.visibility,
      },
      tool: 'create_knowledge_base',
      params,
      message: `Knowledge base "${title}" created successfully`,
      instructions: `## Knowledge Base Created\n\n**${title}** (ID: ${kb.id}, visibility: ${kb.visibility})\n\n### Suggested Next Steps:\n- Use \`create_kb_article\` with kbId="${kb.id}" to add articles\n- Use \`list_knowledge_bases\` to see all knowledge bases`,
    };
  } catch (error) {
    context?.error?.('Error creating knowledge base', { error, params }, 'CreateKnowledgeBaseMacro');
    return {
      success: false,
      error: `Failed to create knowledge base: ${error instanceof Error ? error.message : 'Unknown error'}`,
      tool: 'create_knowledge_base',
      params,
      instructions: `## Create Knowledge Base — Error\n\n${error instanceof Error ? error.message : 'Unknown error'}\n\n### Recovery Options:\n- Verify the input values and retry`,
    };
  }
};

export const CreateKnowledgeBaseMacroDefinition: MacroComponentDefinition<typeof CreateKnowledgeBaseMacro> = {
  nameSpace: 'kb',
  name: 'create_knowledge_base',
  version: '1.0.0',
  component: CreateKnowledgeBaseMacro,
  description: 'Create a new knowledge base for organizing articles and content',
  alias: 'create_knowledge_base',
  runat: 'server',
  icon: 'create_new_folder',
  roles: ['USER', 'ADMIN'],
  tools: [
    {
      type: 'function',
      roles: ['USER', 'ADMIN'],
      function: {
        icon: 'create_new_folder',
        name: 'create_knowledge_base',
        description: 'Create a new knowledge base with specified title, description, and settings',
        parameters: {
          type: 'object',
          properties: {
            title: {
              type: 'string',
              description: 'The title of the knowledge base',
            },
            description: {
              type: 'string',
              description: 'A brief description of what this knowledge base contains',
            },
            lng: {
              type: 'string',
              description: 'Default language code (e.g., "en", "fr", "es")',
              default: 'en',
            },
            visibility: {
              type: 'string',
              enum: ['private', 'public', 'shared', 'organization'],
              description: 'Visibility setting for the knowledge base',
              default: 'private',
            },
            tags: {
              type: 'array',
              items: { type: 'string' },
              description: 'Tags for categorizing the knowledge base',
            },
          },
          required: ['title'],
        },
      },
    },
  ],
};

export default CreateKnowledgeBaseMacroDefinition;
